### ISSUE TITLE
tasks priority - marcosptf

### ISSUE THREAD

**Issue by marcosptf** [marcosptf/fedora#31]
+Spécialisation:
->php-src
->magento
->netbeans/plugins
->java architect

+TASKS
1. $=> novatec -> flask
2. $=> novatec -> sugestions => (respect, drupal, prestashop, yii, laravel, cake, phalcon, silex, plone);
3. $=> google play -> app published
4.mozilla add-on
5.chrome extensions
6. $=> apple store -> app published
7.http://php.net/manual/en/internals2.ze1.zendapi.php
8.php-src => https://github.com/marcosptf/fedora/issues/40 
9.http://bugs.php.net/
10.https://www.hackerrank.com/feed
11.http://phpclasses.org/ review + tutorial + classes + daily
12.netbeans -> new plugin twitter || reddit 
13. $=> compacta print camisetas nerds

=================================================================>
+Targets 2016
-><priority>write a book to novatec Respect - "Construa grandes app usando Respect"</priority>

->commit @marcosptf =>
-google play
-apple store
-samsung store
-steam app store
-opera store
-mozilla add-on
-chrome extensions

->fedoralfs <labs/>

->be php hacker
https://github.com/pear/pear-core
http://php.net/manual/en/internals2.ze1.php
http://php.net/manual/en/internals2.php
php-src contribute https://github.com/marcosptf/fedora/issues/40

->create php extension 
-http://pecl.php.net/ https://github.com/marcosptf/fedora/issues/39

->just to play =>
http://www.phpclasses.org/
https://www.hackerrank.com/leaderboard
https://github.com/pear/pear-core (http://pear.php.net/bugs/stats_dev.php)

->c++ developer
-https://github.com/php/php-gtk-src https://github.com/marcosptf/fedora/issues/25

->keep writing php articles to phpsp/http://www.phpclasses.org/ 
-php with metaprogramming
-php di
-php with concurrency
-arduino php

====================================================================
+anothers tasks
===>to do
9.frameworks php - learn enhancement
https://github.com/marcosptf/fedora/issues/38
10.software engineer
10.1 Design Patterns - https://github.com/domnikl/DesignPatternsPHP
10.2 DDD

 ========================================================================>
+normals (sorting) tasks
-a new name to new fedora-lfs version enhancement
-speaker fight - pycon11 enhancement
-hackerias enhancement
-learn java spring to web develop enhancement
-java ejb book enhancement
http://www.slideshare.net/rdohms/annotations-in-php-they-exist

 ========================================================================>
+Médailles des programmation - we've got
1.php
https://github.com/php/php-src/search?q=marcosptf
https://github.com/php/php-src/graphs/contributors?from=2015-01-01&to=2015-10-06&type=c
https://github.com/php/php-src/pulls/marcosptf
https://bugs.php.net/bug.php?id=70659&thanks=4
https://bugs.php.net/bug.php?id=70826&thanks=4
https://bugs.php.net/bug.php?id=70827&thanks=4
https://bugs.php.net/bug.php?id=70847&thanks=4
https://bugs.php.net/bug.php?id=70856&thanks=4
https://bugs.php.net/bug.php?id=70840
https://bugs.php.net/bug.php?id=70936&thanks=2
https://bugs.php.net/bug.php?id=70935&thanks=4

2.netbeans/java
https://netbeans.org/bugzilla/buglist.cgi?bug_status=NEW&bug_status=STARTED&bug_status=REOPENED&email1=marcosptf%40netbeans.org&emailassigned_to1=1&emailreporter1=1&emailtype1=exact&field0-0-0=bug_status&field0-0-1=reporter&list_id=783137&type0-0-0=notequals&type0-0-1=equals&value0-0-0=UNCONFIRMED&value0-0-1=marcosptf%40netbeans.org
https://netbeans.org/people/155724-marcos-paulo
http://plugins.netbeans.org/plugin/59448/?show=true
http://plugins.netbeans.org/plugin/60090/?show=true
https://netbeans.org/bugzilla/show_bug.cgi?id=255283
https://netbeans.org/bugzilla/show_bug.cgi?id=255022

3.python
http://bugs.python.org/issue24930

4.
winner in hacker event
https://flic.kr/p/yAZtPN

5.
keynote speaker
-speaker about flask in pybr11
https://www.facebook.com/pythonbrasil/photos/a.802266406462553.1073741826.328258703863328/1041401229215735/?type=3
-speaker about development in php source code core
https://twitter.com/phpsp/status/665515671950909440

6.
tecnical writer in famous blog in Brazil
http://phpsp.org.br/author/marcosptf/
http://www.phpclasses.org/blog/post/386-How-to-Contribute-to-PHP-Development-Writing-phpt-Tests.html

7.
i'm part of the team the core developers that contribute to php7
http://devzone.zend.com/6956/php-7-core-contributors-thankyou/

8.
what the people told about me?
[comments  from twitter/fb/meetup]

Médailles des programmation - we want to do
0.http://conferences.oreilly.com/oscon/open-source/public/cfp/423
1.https://github.com/pear/pear-core (http://pear.php.net/bugs/stats_dev.php)
2.https://github.com/php/php-gtk-src
3.http://pecl.php.net/account-request.php ( https://github.com/marcosptf/fedora/issues/39 )
4.https://github.com/phalcon/cphalcon
5.https://www.hackerrank.com/leaderboard
6.http://www.phpclasses.org/winners/
7.http://www.zend.com/en/company/careers/senior-cc-developer
Senior C/C++ Developer - jobs@zend.com
Skills and Experience: 
    Minimum 5 years of experience of C/C++ development in a Linux/Unix/Windows environment
    In-depth knowledge of Linux at system programming level (Processes and Threads, Memory management, IPC, TCP/IP networking)
    Deep knowledge of development tools (Makefile, Qmake, configure)
    Deep knowledge of source control systems (SVN, git, etc.)
    Skilled in debugging using gdb, strace and other Linux-based tools
    Experience in shell scripting
    Very good acquaintance of web environment (HTTP, JSON, XML, etc.)
    Computer Sciences Bachelor degree – or equivalent
    Outstanding communication skills both in Hebrew and English
    Self-motivated, independent worker – that can also work great inside a team

Advantage, but not a must: 
    Experience in C/C++ under Windows (including system knowledge, debugging with VS/WinDbg, etc.)
    PHP Engine internals / writing PHP plug-ins
    Acquaintance with Linux/Apache/MySQL/PHP (LAMP)
    Customer interaction experience, incl. product troubleshooting in complex environments.
    Experience with SQL
    Experience with Open Source software projects
    Experience with QT framework

===============================================================
-learn these tools:
http://devdocs.magento.com/guides/m1x/index.html
http://symfony.com/doc/current/index.html

-marcosptf@php.net
https://bugs.php.net/login.php

+develop a c util program to fedora or something else

===============================================================

**Comment by p0w34007** [comment]
fedora ask badges:
https://ask.fedoraproject.org/en/badges/

fedora dev badges;
https://badges.fedoraproject.org

fedora 
https://fedoraproject.org/wiki/SIGs/PHP
https://developer.fedoraproject.org
https://fedoraproject.org/wiki/Category:Package_Maintainers
